version: '3.8'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  backend:
    build: ../backend/
    restart: always
    volumes:
      - media_value:/app/media/
      - static_value:/app/static/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_foodgram/
      - media_value:/var/html/media/

volumes:
  media_value:
  static_value:
