version: '3.8'
services:

  database:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  frontend:
    image: hotosho/foodgram_frontend:latest
    volumes:
      # - ../frontend/:/app/result_build/
      - result_build:/app/result_build/build/
  backend:
    image: hotosho/foodgram_final:latest
    restart: always
    volumes:
      - media_value:/app/media/
      - static_value:/app/static/
      - redoc_data:/app/docs/
    env_file:
      - ./.env
    depends_on:
      - database
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - result_build:/usr/share/nginx/html/
      - redoc_data:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_foodgram/
      - media_value:/var/html/media/

volumes:
  media_value:
  static_value:
  postgres_data:
  result_build:
  redoc_data:
