# Generated by Django 4.1 on 2022-09-15 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=256, verbose_name="Name")),
                (
                    "measurement_unit",
                    models.TextField(max_length=256, verbose_name="Measurement unit"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=256, verbose_name="Name")),
                (
                    "color",
                    models.TextField(
                        default="#ffffff", max_length=7, verbose_name="HexColor"
                    ),
                ),
                (
                    "slug",
                    models.TextField(
                        blank=True, max_length=256, null=True, verbose_name="Slug"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=256, verbose_name="Name")),
                ("image", models.ImageField(upload_to="recipe_images/")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cooking_time",
                    models.PositiveIntegerField(verbose_name="Cooking time in minutes"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("components", models.ManyToManyField(to="recipes.component")),
                ("tags", models.ManyToManyField(to="recipes.tag")),
            ],
            options={
                "ordering": ("author",),
            },
        ),
    ]
