# Generated by Django 4.1 on 2022-09-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_favoriterecipe_ingredientrecipe_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favoriterecipe",
            name="favorite_recipes_constraint",
        ),
        migrations.AddConstraint(
            model_name="favoriterecipe",
            constraint=models.UniqueConstraint(
                fields=("author", "recipe"), name="favorite_recipes_constraint"
            ),
        ),
    ]
