# Generated by Django 4.1 on 2022-09-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_favoriterecipe_favorite_recipes_constraint_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="text",
        ),
    ]
