# Generated by Django 4.1 on 2022-10-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_shoppingcart_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favoriterecipe",
            name="favorite_recipes_constraint",
        ),
        migrations.RenameField(
            model_name="favoriterecipe",
            old_name="author",
            new_name="user",
        ),
        migrations.AddConstraint(
            model_name="favoriterecipe",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="favorite_recipes_constraint"
            ),
        ),
    ]
