# Generated by Django 4.1 on 2022-09-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_favoriterecipe_favorite_recipes_constraint_and_more"),
        ("users", "0002_shoppingcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="recipes",
            field=models.ManyToManyField(
                related_name="in_shopping_cart", to="recipes.recipe"
            ),
        ),
    ]
