# Generated by Django 4.1 on 2022-10-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_shoppingcart_recipes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShoppingCart",
        ),
    ]
