# Generated by Django 4.1 on 2022-10-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subscribeuser_subscribeuser_subscription_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-pk"]},
        ),
    ]
